"""
Match Score Schemas.

Defines Pydantic models for job-candidate matching results.
"""
from typing import List, Optional
from datetime import datetime
from pydantic import BaseModel, Field


class MatchScore(BaseModel):
    """
    Match score between a resume and a job listing.

    Generated by the LLM-based matching engine.
    """
    job_id: str = Field(
        ...,
        description="ID of the matched job"
    )
    match_score: int = Field(
        ...,
        ge=0,
        le=100,
        description="Match score from 0-100"
    )
    reason: str = Field(
        ...,
        description="Explanation for the match score"
    )
    matched_skills: List[str] = Field(
        default_factory=list,
        description="Skills from the resume that match the job"
    )
    missing_skills: List[str] = Field(
        default_factory=list,
        description="Skills in the job that are missing from the resume"
    )
    heuristic_score: int = Field(
        ...,
        ge=0,
        le=100,
        description="Pre-LLM heuristic match score"
    )

    class Config:
        extra = "ignore"
        strict = True
        json_schema_extra = {
            "example": {
                "job_id": "job_12345",
                "match_score": 85,
                "reason": "Strong match on Python, React, and AWS experience. Candidate has relevant backend development background.",
                "matched_skills": ["Python", "React", "AWS", "Docker"],
                "missing_skills": ["Kubernetes", "Terraform"],
                "heuristic_score": 78
            }
        }


class MatchedJob(MatchScore):
    """Match score combined with full job details."""
    job: dict = Field(
        ...,
        description="Full job listing details"
    )

    class Config:
        json_schema_extra = {
            "example": {
                **MatchScore.Config.json_schema_extra["example"],
                "job": {
                    "id": "job_12345",
                    "title": "Senior Software Engineer",
                    "company": "Tech Corporation",
                    "location": "San Francisco, CA",
                    "description": "We are looking for...",
                    "source": "indeed"
                }
            }
        }


class MatchResponse(BaseModel):
    """Response after matching a resume to jobs."""
    total_matches: int
    matched_jobs: List[MatchedJob]
    processing_time_ms: int

    class Config:
        json_schema_extra = {
            "example": {
                "total_matches": 25,
                "processing_time_ms": 1250,
                "matched_jobs": [MatchedJob.Config.json_schema_extra["example"]]
            }
        }


class HeuristicMatch(BaseModel):
    """
    Heuristic-only match score (before LLM scoring).

    Used for pre-filtering jobs before expensive LLM calls.
    """
    job_id: str
    score: int
    skills_matched: List[str]
    skills_missing: List[str]
    skill_overlap_percentage: float

    class Config:
        json_schema_extra = {
            "example": {
                "job_id": "job_12345",
                "score": 78,
                "skills_matched": ["Python", "React", "AWS"],
                "skills_missing": ["Kubernetes", "Terraform"],
                "skill_overlap_percentage": 60.0
            }
        }
